@host=http://localhost:8009

### Тестирование эндпоинта
GET {{host}}/ping

### Отправка
POST {{host}}/save-email
Content-Type: application/json

{
    "email": "alikosh"
}

### Получение
GET {{host}}/get-emails
Accept: application/json
